apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "2358"
      port: 2358
      targetPort: 2358
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
